DROP TABLE IF EXISTS vehicle CASCADE;
CREATE TABLE vehicle (id bigserial PRIMARY KEY NOT NULL, carModel varchar(60), ManufactureDate date, UserId bigint REFERENCES users (id));

/*CREATE FUNCTION getRandomUserID() RETURNS bigint AS '
    SELECT id
    FROM users
    ORDER BY random()
    LIMIT 1
' LANGUAGE sql;*/

insert into vehicle (carModel, ManufactureDate, UserId) values ('Sierra', '2011-12-27', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('RX-7', '1916-07-12', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('S2000', '1996-08-15', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('XK', '1958-11-04', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Savana 1500', '1990-04-11', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Quest', '1906-04-27', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Grand Prix', '1913-03-22', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('APV', '1969-04-29', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Elise', '1978-03-20', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Gallardo', '1996-04-29', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Club Wagon', '1911-03-06', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('5 Series', '2008-12-20', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('XC60', '1961-04-23', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Boxster', '1985-10-17', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Navigator', '1906-08-23', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Stealth', '1991-03-30', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Range Rover', '1988-12-04', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Grand Prix', '1926-01-10', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('SL-Class', '1920-01-14', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Firebird', '1968-01-19', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Camry Hybrid', '1929-12-06', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('850', '1922-01-03', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Mustang', '2020-06-17', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Sidekick', '1995-11-05', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Escalade', '1967-04-17', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Eos', '1919-11-06', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('SC', '2012-12-31', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('5 Series', '1982-11-07', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Yaris', '1924-03-16', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Outlander', '1965-10-31', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('TSX', '1975-04-24', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Impreza', '2016-07-21', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('F250', '1912-11-15', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Civic', '2017-01-29', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Bonneville', '1929-05-04', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('9000', '1998-06-05', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('GS', '1974-09-02', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Optima', '2018-03-06', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Camaro', '1904-04-13', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('1500', '1998-10-13', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Cabriolet', '2014-12-04', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Continental', '1913-04-05', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('LS', '1968-11-12', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('626', '1991-05-21', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Terrain', '1955-11-11', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('XG350', '1954-12-17', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Riviera', '1915-02-18', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('SSR', '1961-11-23', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Yukon', '1943-01-20', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('MDX', '2016-11-01', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Continental', '1968-12-19', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Stealth', '1914-08-26', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('CC', '2008-08-27', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Silverado 2500', '1948-10-24', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Lancer', '2014-06-23', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Elantra', '1958-11-25', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Tempo', '1924-03-14', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Tahoe', '1981-01-14', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('9-3', '1946-04-15', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('CR-V', '1921-02-22', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Rio', '1945-06-05', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('100', '1959-01-28', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Prius', '1978-03-03', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Passport', '1932-04-09', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Ghost', '1936-01-05', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('2500', '2008-08-23', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('TL', '1901-08-18', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('MR2', '1948-06-23', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Grand Marquis', '1999-08-22', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('NSX', '1909-10-10', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Neon', '1974-06-11', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Continental Flying Spur', '1938-01-27', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('MX-5', '2008-09-03', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Suburban 1500', '2000-02-26', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('929', '2005-07-16', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Vitara', '1916-07-14', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Suburban 2500', '1903-02-15', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('S2000', '1975-09-14', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('X6', '2010-11-30', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Amigo', '2010-12-21', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Tribute', '1974-05-20', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Grand Caravan', '2003-10-16', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Yaris', '1934-02-10', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Regal', '1994-06-30', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Firefly', '1922-08-01', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Th!nk', '1912-04-07', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Aurora', '1904-10-11', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('DeVille', '2005-03-08', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Suburban 1500', '1907-08-11', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('228', '1953-06-16', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Cherokee', '2000-10-04', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Sonoma', '1967-11-25', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('XL7', '1910-03-05', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Econoline E150', '1933-12-10', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Aveo', '1929-02-24', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Custom Cruiser', '1925-03-16', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Voyager', '1974-02-17', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('LeSabre', '2016-04-10', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('V8', '1966-04-18', getRandomUserID());
insert into vehicle (carModel, ManufactureDate, UserId) values ('Grand Am', '1948-02-07', getRandomUserID());